name: Build Einfach Billig App

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Python einrichten
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Programme installieren
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip install --upgrade Cython==0.29.33 virtualenv buildozer

      - name: APK bauen
        run: yes | buildozer -v android debug

      - name: APK hochladen
        uses: actions/upload-artifact@v4
        with:
          name: einfach-billig-app-apk
          path: bin/*.apk
