name: Build Einfach Billig App

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer -v android debug
      - uses: actions/upload-artifact@v4
        with:
          name: einfach-billig-app-apk
          path: bin/*.apk
